### ISSUE TITLE
Circleci Mysql Kurulum Sorunu

### ISSUE THREAD

**Issue by mehmetadil** [mehmetadil/translator#1]
Hata Mesajı: 

```#!/bin/bash -eo pipefail
bin/rails db:schema:load --trace
** Invoke db:schema:load (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config (first_time)
** Execute db:load_config
** Invoke db:check_protected_environments (first_time)
** Invoke environment 
** Invoke db:load_config 
** Execute db:check_protected_environments
rails aborted!
Mysql2::Error: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.9/lib/mysql2/client.rb:89:in `connect'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.9/lib/mysql2/client.rb:89:in `initialize'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/mysql2_adapter.rb:21:in `new'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/mysql2_adapter.rb:21:in `mysql2_connection'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:759:in `new_connection'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:803:in `checkout_new_connection'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:782:in `try_to_checkout_new_connection'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:743:in `acquire_connection'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:500:in `checkout'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:374:in `connection'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `retrieve_connection'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_handling.rb:116:in `retrieve_connection'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_handling.rb:88:in `connection'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1038:in `current_version'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1271:in `last_stored_environment'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:56:in `check_protected_environments!'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:11:in `block (2 levels) in <top (required)>'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/lib/rake/task.rb:251:in `block in execute'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/lib/rake/task.rb:251:in `each'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/lib/rake/task.rb:251:in `execute'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/lib/rake/task.rb:217:in `block in invoke_prerequisites'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/lib/rake/task.rb:215:in `each'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/lib/rake/task.rb:215:in `invoke_prerequisites'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/lib/rake/task.rb:181:in `invoke'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/lib/rake/application.rb:153:in `invoke_task'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/lib/rake/application.rb:109:in `block (2 levels) in top_level'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/lib/rake/application.rb:109:in `each'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/lib/rake/application.rb:109:in `block in top_level'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/lib/rake/application.rb:118:in `run_with_threads'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/lib/rake/application.rb:103:in `top_level'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/lib/rake/application.rb:179:in `standard_exception_handling'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/command.rb:46:in `invoke'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
/home/circleci/myapp/bin/rails:9:in `require'
/home/circleci/myapp/bin/rails:9:in `<top (required)>'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
/home/circleci/myapp/vendor/bundle/ruby/2.3.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
/home/circleci/myapp/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:schema:load => db:check_protected_environments
Exited with code 1
```

Konfigürasyon dosyası : 

```
version: 2
jobs:
  build:
    working_directory: ~/myapp
    docker:
      - image: circleci/ruby:2.3-node
        environment:
          PGHOST: 127.0.0.1
          PGUSER: myapp-test
          RAILS_ENV: test
      - image: circleci/mysql:5.7
        environment:
        - MYSQL_ROOT_PASSWORD=ubuntu
        - MYSQL_DATABASE=circle_test
    steps:
      - checkout

      - restore_cache:
          name: Restore bundle cache
          keys:
            - myapp-bundle-{{ checksum "Gemfile.lock" }}
            - myapp-bundle-

      - restore_cache:
          name: Restore yarn cache
          keys:
            - myapp-yarn-{{ checksum "yarn.lock" }}
            - myapp-yarn-

      - run:
          name: Bundle Install
          command: bin/bundle check --path vendor/bundle ||  bin/bundle install --path vendor/bundle --jobs 4 --retry 3

      - save_cache:
          name: Store bundle cache
          key: myapp-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      - run:
          name: Run tests
          command: bin/rails test
```
